// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbLajspIOeaZTUS64f1EsGqY85tJjz520',
    appId: '1:347224372745:web:4a03a714c7fd9bd2e0aad8',
    messagingSenderId: '347224372745',
    projectId: 'dynamiapp-d21ee',
    authDomain: 'dynamiapp-d21ee.firebaseapp.com',
    storageBucket: 'dynamiapp-d21ee.firebasestorage.app',
    measurementId: 'G-E2V426VZG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUfqqx0DFKUdJvjPon-e5sFTF1z2rV00',
    appId: '1:347224372745:android:386daa3eb0bcc5c7e0aad8',
    messagingSenderId: '347224372745',
    projectId: 'dynamiapp-d21ee',
    storageBucket: 'dynamiapp-d21ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5K-F6kKFg1fXXWwdC3DSZUB9n-seYPZw',
    appId: '1:347224372745:ios:99db92622b207374e0aad8',
    messagingSenderId: '347224372745',
    projectId: 'dynamiapp-d21ee',
    storageBucket: 'dynamiapp-d21ee.firebasestorage.app',
    iosBundleId: 'com.example.dynamicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5K-F6kKFg1fXXWwdC3DSZUB9n-seYPZw',
    appId: '1:347224372745:ios:99db92622b207374e0aad8',
    messagingSenderId: '347224372745',
    projectId: 'dynamiapp-d21ee',
    storageBucket: 'dynamiapp-d21ee.firebasestorage.app',
    iosBundleId: 'com.example.dynamicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbLajspIOeaZTUS64f1EsGqY85tJjz520',
    appId: '1:347224372745:web:e90e83937f07ad1fe0aad8',
    messagingSenderId: '347224372745',
    projectId: 'dynamiapp-d21ee',
    authDomain: 'dynamiapp-d21ee.firebaseapp.com',
    storageBucket: 'dynamiapp-d21ee.firebasestorage.app',
    measurementId: 'G-ZBBSDD4CHR',
  );
}
